### ISSUE TITLE
Roadmap: Generative Manim Suite

### ISSUE THREAD

**Issue by 360macky** [360macky/generative-manim#6]
# Engines

An engine is a complete text-to-code and code-to-video generation system for Generative Manim (GM). Since there are many ways we can think about video generation, we developed multiple engines so that they can be evaluated with [LangSmith](https://smith.langchain.com).

- [ ] GM powered by DSL
- [x] GM powered by LangGraph
- [ ] GM OpenAI Fine-tuned
- [ ] GM OpenAI GPT-4 with Few-Shot Learning
- [ ] GM OpenAI GPT-4 with Zero-Shot Learning
- [ ] GM OpenAI GPT-4 with Ontologies/RAG

Anyone can suggest a new way (workflow, method, technique) to generate videos.

# Platforms

## API

Generative Manim will be available with a REST API.

- [x] Create `/code-to-video` endpoint (Ready)
- [ ] Create `/text-to-code` endpoint (To be enhanced)
  - [ ] Add an option to switch between different GM engines (e.g. DSL, Ontologies, etc.)
  - [ ] Add first model (the simplest one, using GPT-4 with few-shot training and zero shot learning)

## LangChain Integration

- [ ] Create a package over LangChain?

## GPT / Chatbot

- [ ] OpenAPI YAML file with API endpoints

## Streamlit

- [x] New OpenAI API Key
- [x] Integrate new system to detect possible errors on Streamlit

## Testing

- [ ] Define how to test the results of GM engines, in order to choose the best. From the best engine that makes the best result, to the best engine with the lowest usage of tokens.
